# Generated by Django 6.0.7 on 2026-07-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('compliance_issue_raised', 'New compliance issue raised'), ('csr_approval_decision', 'CSR approval decision'), ('challenge_approval_decision', 'Challenge approval decision'), ('policy_ack_reminder', 'Policy acknowledgement reminder'), ('badge_unlocked', 'Badge unlocked'), ('compliance_issue_overdue', 'Compliance issue overdue')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('compliance_issue_raised', 'New compliance issue raised'), ('csr_approval_decision', 'CSR approval decision'), ('challenge_approval_decision', 'Challenge approval decision'), ('policy_ack_reminder', 'Policy acknowledgement reminder'), ('badge_unlocked', 'Badge unlocked'), ('compliance_issue_overdue', 'Compliance issue overdue')], max_length=40)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'type')},
            },
        ),
    ]
