# Generated by Django 6.0.7 on 2026-07-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('manufacturing', 'Manufacturing'), ('expense', 'Expense'), ('fleet', 'Fleet')], max_length=20)),
                ('unit', models.CharField(help_text='Unit the factor applies to, e.g. kg, litre, kWh, km', max_length=30)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('manufacturing', 'Manufacturing'), ('expense', 'Expense'), ('fleet', 'Fleet')], max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Reference id/number of the originating Purchase/Manufacturing/Expense/Fleet record', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculated_emission', models.DecimalField(decimal_places=4, editable=False, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('is_auto_calculated', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_transactions', to='core.department')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carbon_transactions', to='environmental.emissionfactor')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='e.g. kg CO2e to reduce to', max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(default='kgCO2e', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('archived', 'Archived')], default='active', max_length=10)),
                ('department', models.ForeignKey(blank=True, help_text='Blank = organization-wide goal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_goals', to='core.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductESGProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=150)),
                ('product_code', models.CharField(max_length=60, unique=True)),
                ('sustainability_notes', models.TextField(blank=True)),
                ('recyclable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_profiles', to='environmental.emissionfactor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
