# Generated by Django 6.0.7 on 2026-07-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(unique=True)),
                ('environmental_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('social_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('governance_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='Reporting period, e.g. first day of the month/quarter')),
                ('environmental_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('social_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('governance_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.department')),
            ],
            options={
                'ordering': ['-period', '-total_score'],
                'unique_together': {('department', 'period')},
            },
        ),
    ]
